// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultipleDatabases.DAL.ProviderContexts;
using Oracle.EntityFrameworkCore.Metadata;

namespace MultipleDatabases.DAL.Migrations.Oracle
{
    [DbContext(typeof(OracleTestDbContext))]
    partial class OracleTestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("MultipleDatabases.DAL.Models.TestOne", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("Condition")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("Number")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Text")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("TestOnes");
                });

            modelBuilder.Entity("MultipleDatabases.DAL.Models.TestTwo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Test")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid?>("TestOneId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("TestOneId");

                    b.ToTable("TestTwos");
                });

            modelBuilder.Entity("MultipleDatabases.DAL.Models.TestTwo", b =>
                {
                    b.HasOne("MultipleDatabases.DAL.Models.TestOne", null)
                        .WithMany("Elems")
                        .HasForeignKey("TestOneId");
                });
#pragma warning restore 612, 618
        }
    }
}
